# this file is part of the mcbes project
#   _  _   ___  ____  ____      ____ 
#  ( \/ ) / __)(  _ \(  __)___ / ___)
#  / \/ \( (__  ) _ ( ) _)(___)\___ \
#  \_)(_/ \___)(____/(____)    (____/

class ProtocolInfo:
    PROTOCOL_VERSION = 9
    MCPE_VERSION_STRING = "v0.6.1"
    MCPE_VERSION_NETWORK = "0.6.1"
    
    LOGIN_PACKET = 0x82
    LOGIN_STATUS_PACKET = 0x83
    READY_PACKET = 0x84
    MESSAGE_PACKET = 0x85
    SET_TIME_PACKET = 0x86
    START_GAME_PACKET = 0x87
    ADD_MOB_PACKET = 0x88
    ADD_PLAYER_PACKET = 0x89
    REMOVE_PLAYER_PACKET = 0x8A
    ADD_ENTITY_PACKET = 0x8C
    REMOVE_ENTITY_PACKET = 0x8D
    ADD_ITEM_ENTITY_PACKET = 0x8E
    TAKE_ITEM_ENTITY_PACKET = 0x8F
    MOVE_ENTITY_PACKET = 0x90
    MOVE_ENTITY_POSROBOT_PACKET = 0x93
    MOVE_PLAYER_PACKET = 0x94
    PLACE_BLOCK_PACKET = 0x95
    REMOVE_BLOCK_PACKET = 0x96
    UPDATE_BLOCK_PACKET = 0x97
    ADD_PAINTING_PACKET = 0x98
    EXPLODE_PACKET = 0x99
    LEVEL_EVENT_PACKET = 0x9A
    TILE_EVENT_PACKET = 0x9B
    ENTITY_EVENT_PACKET = 0x9C
    REQUEST_CHUNK_PACKET = 0x9D
    CHUNK_DATA_PACKET = 0x9E
    PLAYER_EQUIPMENT_PACKET = 0x9F
    PLAYER_ARMOR_EQUIPMENT_PACKET = 0xA0
    INTERACT_PACKET = 0xA1
    USE_ITEM_PACKET = 0xA2
    PLAYER_ACTION_PACKET = 0xA3
    HURT_ARMOR_PACKET = 0xA5
    SET_ENTITY_DATA_PACKET = 0xA6
    SET_ENTITY_MOTION_PACKET = 0xA7
    SET_HEALTH_PACKET = 0xA8
    SET_SPAWN_POSITION_PACKET = 0xA9
    ANIMATE_PACKET = 0xAA
    RESPAWN_PACKET = 0xAB
    SET_INVENTORY_PACKET = 0xAC
    DROP_ITEM_PACKET = 0xAD
    CONTAINER_OPEN_PACKET = 0xAE
    CONTAINER_CLOSE_PACKET = 0xAF
    CONTAINER_SET_SLOT_PACKET = 0xB0
    CONTAINER_SET_DATA_PACKET = 0xB1
    CONTAINER_SET_CONTENT_PACKET = 0xB2
    CONTAINER_ACK_PACKET = 0xB3
    CHAT_PACKET = 0xB4
    SIGN_UPDATE_PACKET = 0xB5
    ADVENTURE_SETTINGS_PACKET = 0xB6
    
